# Generated by Django 4.1.13 on 2024-07-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_supply'),
        ('purchases', '0003_solicitudzelle_delete_purchasezelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudZelleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.solicitudzelle')),
            ],
        ),
    ]
