# Generated by Django 4.1.13 on 2024-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_solicitudzelle_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudzelle',
            name='entrega',
            field=models.CharField(choices=[('pending', 'En espera'), ('pending', 'En camino'), ('accepted', 'Entregada'), ('canceled', 'Cancelada')], default='pending', max_length=10),
        ),
    ]
