# Generated by Django 4.1.13 on 2024-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_solicitudzelle_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='entrega',
            field=models.CharField(choices=[('pending', 'En espera'), ('onway', 'En camino'), ('accepted', 'Entregada'), ('canceled', 'Cancelada')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudzelle',
            name='entrega',
            field=models.CharField(choices=[('pending', 'En espera'), ('onway', 'En camino'), ('accepted', 'Entregada'), ('canceled', 'Cancelada')], default='pending', max_length=10),
        ),
    ]
