# Generated by Django 4.1.13 on 2024-08-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_remove_purchase_product_solicitudstripeitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='stripe_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
