# Generated by Django 4.1.13 on 2024-08-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_purchase_stripe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='stripe_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
