# Generated by Django 4.1.13 on 2024-08-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_purchase_stripe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudstripeitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='solicitudstripeitem',
            name='solicitud',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='SolicitudStripeItem',
        ),
    ]
