# Generated by Django 4.2 on 2024-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_remove_solicitudstripeitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudzelleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='solicitudzelleitem',
            name='solicitud',
        ),
        migrations.DeleteModel(
            name='SolicitudZelle',
        ),
        migrations.DeleteModel(
            name='SolicitudZelleItem',
        ),
    ]
