# Generated by Django 4.2 on 2024-08-22 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0020_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0012_remove_solicitudzelleitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudZelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('file', models.FileField(upload_to='purchase_files')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('payment_verification_code', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En espera'), ('accepted', 'Aceptada'), ('canceled', 'Cancelada')], default='pending', max_length=10)),
                ('entrega', models.CharField(choices=[('pending', 'En espera'), ('onway', 'En camino'), ('accepted', 'Entregada'), ('canceled', 'Cancelada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='purchases', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudZelleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.solicitudzelle')),
            ],
        ),
    ]
