# Generated by Django 5.0.3 on 2024-04-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
