# Generated by Django 4.2 on 2024-08-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('carnet_de_identidad', models.CharField(blank=True, max_length=11, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra.municipio')),
            ],
        ),
    ]
