# Generated by Django 4.2 on 2024-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='instrucciones_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
