# Generated by Django 4.2 on 2024-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_destinatario_instrucciones_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
            ],
        ),
    ]
