# Generated by Django 4.2 on 2024-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0006_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen_peque',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
    ]
