# Generated by Django 4.2 on 2024-08-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_destinatario_instrucciones_entrega'),
        ('pedidos_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra.destinatario'),
        ),
    ]
