# Generated by Django 4.2 on 2024-08-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_stripe', '0002_purchase_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='handle',
            field=models.CharField(default='CC844EC304ED', editable=False, max_length=12, unique=True),
        ),
    ]
