# Generated by Django 4.2 on 2024-08-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_stripe', '0003_purchase_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudstripeitem',
            name='handle',
            field=models.CharField(default='2D13D565D167', editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='handle',
            field=models.CharField(default='262362DAE60B', editable=False, max_length=12, unique=True),
        ),
    ]
