# Generated by Django 4.2 on 2024-08-22 19:26

from django.db import migrations, models
import pedidos_stripe.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_stripe', '0004_solicitudstripeitem_handle_alter_purchase_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='handle',
            field=models.CharField(default=pedidos_stripe.models.generate_unique_handle, editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudstripeitem',
            name='handle',
            field=models.CharField(default=pedidos_stripe.models.generate_unique_handle, editable=False, max_length=6, unique=True),
        ),
    ]
