# Generated by Django 4.2 on 2024-08-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_destinatario_instrucciones_entrega'),
        ('pedidos_stripe', '0007_purchase_destinatario_delete_pedidodestinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='purchase',
            name='apellidos',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='purchase',
            name='carnet_de_identidad',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='instrucciones_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extra.municipio'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
