# Generated by Django 4.2 on 2024-08-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_stripe', '0008_remove_purchase_destinatario_purchase_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudstripeitem',
            name='product_name_snapshot',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudstripeitem',
            name='product_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
