# Generated by Django 4.1.13 on 2024-07-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
