# Generated by Django 4.1.13 on 2024-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supply',
            field=models.IntegerField(default=1),
        ),
    ]
