# Generated by Django 4.1.13 on 2024-08-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_clasificacion_product_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.clasificacion'),
        ),
    ]
