# Generated by Django 4.1.13 on 2024-08-11 16:03

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_clasificacion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Alain\\Downloads\\PortableGit\\micro_ecommerce\\local-cdn\\protected'), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
