# Generated by Django 4.1.13 on 2024-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_clasificacionpadre_alter_productimage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clasificaciones_padre',
            field=models.ManyToManyField(blank=True, related_name='productos_padre', to='products.clasificacionpadre'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='product',
            name='clasificacion',
            field=models.ManyToManyField(blank=True, related_name='productos', to='products.clasificacionhija'),
        ),
    ]
