# Generated by Django 4.1.13 on 2024-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_clasificaciones_padre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clasificaciones_padre',
            new_name='clasificacionesPadre',
        ),
        migrations.AlterField(
            model_name='product',
            name='clasificacion',
            field=models.ManyToManyField(blank=True, related_name='pro', to='products.clasificacionhija'),
        ),
    ]
