# Generated by Django 4.1.13 on 2024-08-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_clasificaciones_padre_product_clasificacionespadre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clasificacionesPadre',
            new_name='clasificaciones_padre',
        ),
    ]
