# Generated by Django 4.1.13 on 2024-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_clasificacionespadre_product_clasificaciones_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
