# Generated by Django 4.1.13 on 2024-08-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productimage_file'),
        ('products', '0016_product_keywords'),
    ]

    operations = [
    ]
