# Generated by Django 4.2 on 2024-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_productoffer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
