# Generated by Django 4.2 on 2024-08-29 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0031_product_average_rating_alter_productimage_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.CreateModel(
            name='Rating_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_product', to='products.product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='average',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='average', to='products.rating_product'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('average', 'user')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
    ]
