# Generated by Django 4.2 on 2024-08-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_average_rating_rating_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='offer_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=10),
        ),
    ]
