# Generated by Django 4.2 on 2024-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productoffer_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
